import Head from 'next/head'
import { Roboto } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ 
  subsets: ['latin', 'cyrillic'],
  weight: ["300", "400", "700"],//light, regular, bold
  preload: true,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Buketochka Front</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
      </main>
    </>
  )
}
